import React from "react";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
  CartAPI,
  CartDelete,
  CartUpdate,
  cartByUser,
  PostCartItems,
  CartReset,
} from "./cartAPI";

const initialState = {
  CartItems: [],
  status: "idle",
  error: null,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const postItemAsync = createAsyncThunk(
  "users/posttocart",
  async (cartData) => {
    const response = await PostCartItems(cartData);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchCartByUserAsync = createAsyncThunk(
  "users/cartbyuser",
  async (id) => {
    const response = await cartByUser(id);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const updateCartAsync = createAsyncThunk(
  "cart/updatecart",
  async (update) => {
    const response = await CartUpdate(update);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const deleteCartAsync = createAsyncThunk(
  "cart/updatedelete",
  async (id) => {
    const response = await CartDelete(id);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const resetCartAsync = createAsyncThunk(
  "cart/resetCart",
  async (id) => {
    const response = await CartReset(id);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(postItemAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(postItemAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.CartItems.push(action.payload);

        // if (state.CartItems.includes(action.payload)) {
        //   console.log('not here')
        // } else {
        //   state.CartItems.push(action.payload);
        //   console.log('CartItems:', state.CartItems.slice);
        // }
      })
      .addCase(fetchCartByUserAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchCartByUserAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.CartItems = action.payload;
      })
      .addCase(updateCartAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(updateCartAsync.fulfilled, (state, action) => {
        state.status = "idle";
        const index = state.CartItems.findIndex(
          (items) => items.id === action.payload.id
        );
        state.CartItems[index] = action.payload;
      })
      .addCase(deleteCartAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(deleteCartAsync.fulfilled, (state, action) => {
        state.status = "idle";
        const index = state.CartItems.findIndex(
          (items) => items.id === action.payload.itemid
        );
        state.CartItems.splice(index, 1);
      })
      .addCase(resetCartAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(resetCartAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.CartItems = action.payload;
      })
      ;
  },
});

export const { increment, decrement, incrementByAmount } = cartSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCartItems = (state) => state.cart.CartItems;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default cartSlice.reducer;
